version: "3.7"

services:
  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'
    networks:
      app-network:
        ipv4_address: 10.10.0.2

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "8080:9090"
    volumes:
      - "/etc/prometheus:/etc/prometheus"
    networks:
      app-network:
        ipv4_address: 10.10.0.3

  grafana-oss:
    image: grafana/grafana-oss:latest
    container_name: grafana-oss
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - "grafana-storage:/var/lib/grafana"
    networks:
      app-network:
        ipv4_address: 10.10.0.4

  falcosidekick:
    image: falcosecurity/falcosidekick
    container_name: falcosidekick
    restart: unless-stopped
    ports:
      - "2801:2801"
    networks:
      app-network:
        ipv4_address: 10.10.0.5

volumes:
  grafana-storage:
    driver: local

networks:
  app-network:
    ipam:
      driver: default
      config:
        - subnet: "10.10.0.0/24"